name: Benchmark_Speedy
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write
jobs: 
  benchmark:
    name: Run JavaScript benchmark example
    runs-on: ubuntu-latest
    steps:
      - name: checkout current git branch
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      
      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Install Yarn
        run: npm install -g yarn && yarn
      
      - name: Install Hyperfine
        run: npm install -g hyperfine

      - name: Git Download
        run: git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/speedy-js/benchmarks.git && cd benchmarks && git checkout fix/npm8-error && pnpm install && cd -

      - name: Run Hyperfine
        run:  cd benchmarks && npm run bench | tee ../output.txt && cd - 

      - name: Exec GitHub Api
        run: ls && npm run test
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}

      