name: Benchmark_Speedy
on:
  push:

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run JavaScript benchmark example
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      
      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Install Hyperfine
        run: npm install -g hyperfine

      # - name: Git Download
      #   run: git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/speedy-js/benchmarks.git && cd benchmarks && git checkout fix/npm8-error && pnpm install && cd -
      - name: Clone benchmarks
        run: git clone https://github.com/speedy-js/benchmarks && cd benchmarks && git checkout dev && pnpm install && cd -

      - name: Run Benchmark
        run:  cd benchmarks && pnpm bench && cd -

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          # What benchmark tool the output.txt came from
          tool: 'customSmallerIsBetter'
          # Where the output from the benchmark tool is stored
          output-file-path: ./benchmarks/benchmark-runner/dist/bechmark-action-otuput.txt
          # Where the previous data file is stored
          # external-data-json-path: ./cache/benchmark-data.json
          # Workflow will fail when an alert happens
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
      # Upload the updated cache file for the next job by actions/cache